dist: trusty
sudo: false
language: erlang
otp_release:
  - 19.3.6.1
addons:
  apt:
    packages:
      - r-base
before_install:
  - ./ci before_install ${JOB:?} "${TRAVIS_BUILD_DIR:?}"
install:
  - ./ci install ${JOB:?} "${TRAVIS_BUILD_DIR:?}"
before_script:
  - ./ci before_script ${JOB:?} "${TRAVIS_BUILD_DIR:?}"
script:
  - ./ci script ${JOB:?} "${TRAVIS_BUILD_DIR:?}"
matrix:
  allow_failures:
  fast_finish: true
env:
  - JOB=minloadtest
  - JOB=dialyzer
  - JOB=xref
cache:
  directories:
    - .plt
